// src/lib/scrambleWords.ts

export const scrambleWords = [
  // 🟢 EASY
  { word: "coin", hint: "A basic digital unit of value.", difficulty: "Easy" },
  { word: "node", hint: "A computer that helps secure a blockchain.", difficulty: "Easy" },
  { word: "hash", hint: "A unique cryptographic fingerprint.", difficulty: "Easy" },
  { word: "seed", hint: "A secret phrase that secures your wallet.", difficulty: "Easy" },
  { word: "mint", hint: "To create a new token or NFT.", difficulty: "Easy" },
  { word: "gas", hint: "A fee for blockchain transactions.", difficulty: "Easy" },
  { word: "dapp", hint: "Short for decentralized application.", difficulty: "Easy" },
  { word: "swap", hint: "Exchange one token for another.", difficulty: "Easy" },
  { word: "fiat", hint: "Government-issued currency.", difficulty: "Easy" },
  { word: "peer", hint: "Participant in a P2P network.", difficulty: "Easy" },
  { word: "keys", hint: "Used to access your crypto wallet.", difficulty: "Easy" },
  { word: "vote", hint: "Used to participate in DAO decisions.", difficulty: "Easy" },
  { word: "aird", hint: "A reward distribution event.", difficulty: "Easy" },
  { word: "send", hint: "Action to transfer tokens.", difficulty: "Easy" },
  { word: "hold", hint: "Keep tokens for long term (HODL).", difficulty: "Easy" },
  { word: "earn", hint: "Gain rewards or yield.", difficulty: "Easy" },
  { word: "bond", hint: "Lock tokens for returns or governance.", difficulty: "Easy" },
  { word: "link", hint: "Chain or connection between data.", difficulty: "Easy" },
  { word: "farm", hint: "Earn yield by providing liquidity.", difficulty: "Easy" },
  { word: "vote", hint: "Used in decentralized governance.", difficulty: "Easy" },

  // 🟡 MEDIUM
  { word: "wallet", hint: "Stores your crypto safely.", difficulty: "Medium" },
  { word: "airdrop", hint: "Free token distribution to users.", difficulty: "Medium" },
  { word: "staking", hint: "Locking tokens to earn rewards.", difficulty: "Medium" },
  { word: "miner", hint: "Secures blockchain by validating blocks.", difficulty: "Medium" },
  { word: "trading", hint: "Buying and selling crypto assets.", difficulty: "Medium" },
  { word: "privacy", hint: "Core principle of self-sovereign identity.", difficulty: "Medium" },
  { word: "balance", hint: "Total amount in your wallet.", difficulty: "Medium" },
  { word: "billions", hint: "Human and AI verification network.", difficulty: "Medium" },
  { word: "network", hint: "Group of connected nodes.", difficulty: "Medium" },
  { word: "rewards", hint: "Incentives for verified contributors.", difficulty: "Medium" },
  { word: "trust", hint: "Foundation of the new internet.", difficulty: "Medium" },
  { word: "creator", hint: "Someone who builds or contributes.", difficulty: "Medium" },
  { word: "gateway", hint: "Entry point to a decentralized system.", difficulty: "Medium" },
  { word: "referral", hint: "Bring others to the network.", difficulty: "Medium" },
  { word: "digital", hint: "Exists in electronic form.", difficulty: "Medium" },
  { word: "profile", hint: "Your digital identity on the network.", difficulty: "Medium" },
  { word: "message", hint: "Sent between humans or AI agents.", difficulty: "Medium" },
  { word: "builder", hint: "Someone expanding the ecosystem.", difficulty: "Medium" },
  { word: "connect", hint: "Link humans and AI together.", difficulty: "Medium" },
  { word: "humans", hint: "Verified users in the Billions Network.", difficulty: "Medium" },

  // 🔴 HARD
  { word: "blockchain", hint: "The underlying tech for Bitcoin.", difficulty: "Hard" },
  { word: "verification", hint: "Proving authenticity and uniqueness.", difficulty: "Hard" },
  { word: "cryptography", hint: "Mathematical foundation of security.", difficulty: "Hard" },
  { word: "decentralize", hint: "Remove single points of control.", difficulty: "Hard" },
  { word: "interoperable", hint: "Able to work across different chains.", difficulty: "Hard" },
  { word: "zeroKnowledge", hint: "Proof without revealing private data.", difficulty: "Hard" },
  { word: "accountability", hint: "Ensuring humans and AI are traceable.", difficulty: "Hard" },
  { word: "governance", hint: "How decentralized networks make decisions.", difficulty: "Hard" },
  { word: "transparency", hint: "Everything visible and verifiable.", difficulty: "Hard" },
  { word: "smartcontract", hint: "Self-executing code on blockchain.", difficulty: "Hard" },
  { word: "participation", hint: "Active involvement in the ecosystem.", difficulty: "Hard" },
  { word: "collaboration", hint: "Working together across networks.", difficulty: "Hard" },
  { word: "cryptoeconomy", hint: "Economy driven by blockchain systems.", difficulty: "Hard" },
  { word: "reputation", hint: "Earned trust in a network.", difficulty: "Hard" },
  { word: "infrastructure", hint: "The foundation of digital systems.", difficulty: "Hard" },
  { word: "authentication", hint: "Confirming someone’s identity.", difficulty: "Hard" },
  { word: "validator", hint: "Confirms transactions on the network.", difficulty: "Hard" },
  { word: "ecosystem", hint: "Interconnected community of builders.", difficulty: "Hard" },
  { word: "innovation", hint: "What drives new ideas forward.", difficulty: "Hard" },
  { word: "multichain", hint: "Operating across multiple blockchains.", difficulty: "Hard" },
];
